### PR TITLE
Update antora  and site titles

### PR DESCRIPTION
**Pull request by rgleason**

### CODE REVIEW

**Comment by Rasbats** [comment]
Somehow you edited a fork of calculator in opencpn-manuals. 
sources.state shows the source as `https://github.com/rasbats/calculator_pi`
I have used most of the changes you made and made a commit to `https://github.com/rasbats/calculator_pi.` 
I will now update sources.state with the latest commit hash.

**Comment by rgleason** [comment]
I did that on purpose.  
I got you your calculator repository and "forked" and then selected my second user "opencpn-manuals".
It went right into  opencpn-manuals.  
Then I got on the opencpn-manuals/plugins  html page and navigated to calculator
Then I hit the Edit this page button and made the changes and made a commit.
I believe that is what Alec said to do.
I then deleted my first PR from rgleason repos that was forked from Rasbats.
Alec said that if I fork to opencpn-manuals that "All of us will be able to make edits"  
So I expect that that is the best way to work.
Were you not able to just accept the changes from that PR?

**Comment by rgleason** [comment]
> shows sources.state shows the source as https://github.com/rasbats/calculator_pi

That is correct and that is the way it should be.  You would just have to accept the PR.

**Comment by Rasbats** [comment]
I did not seem able to accept the PR.

**Comment by rgleason** [comment]
I wonder why not?  The same PR's from my repos to rasbats/calculator were right there too?

I've done double the edits and you still could not simply merge. Also I've lost all my work on Dashboard and Grib_pi because the build branch was overwritten rather than being merged somehow first!   

**Maybe we should first get a script notice that there are changes in the build branch that have to be reviewed!**   
Also after that notice there should be a defined set of steps to do a proper review and accept the changes.

This process is not going to work. I am having a having a had time imagining rewritingthe Main User Manual this way.

**Pull request closed without merging**
